name: qr_menu
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_vector_icons: ^1.0.0

  # Common packages
  nb_utils: ^4.4.9
  google_fonts: ^2.1.0
  readmore: ^2.1.0
  url_strategy: ^0.2.0
  lottie: ^1.2.1

  # Firebase
  firebase_core: ^1.7.0
  cloud_firestore: ^2.5.3
  firebase_auth: ^3.1.3
  firebase_storage: ^10.0.5
  firebase_analytics: ^8.3.3
  firebase_crashlytics: ^2.2.3

  #  SignIN Methods
  google_sign_in: ^5.1.1
  the_apple_sign_in: ^1.1.1

  # State Management Technique
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2

  # QR Create and Scan
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.5.2

  # Used for image save and pick
  image_picker: ^0.8.4+2
  path_provider: ^2.0.5
  cached_network_image: ^3.1.0
  permission_handler: ^8.1.6
  screenshot: ^1.2.3

  #  Used for App sharing,web View
  url_launcher: ^6.0.12
  share_plus: ^2.1.4
  package_info_plus: ^1.0.6
  grouped_list: ^4.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.2
  mobx_codegen: ^2.0.3
  #flutter packages pub run build_runner build --delete-conflicting-outputs
flutter:

  uses-material-design: true

  assets:
    - images/
    - images/flag/

